version: '3.1'
services:
  # nginx server managing proxies
  nginx:
    image: nginx:1.17
    restart: always
    depends_on:
      - node
    ports:
      - "80:80"
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
    container_name: nginx

  # mysql database
  mysql:
    image: mysql:8.0.18
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
    container_name: mysql

  node:
    build: node
    restart: always
    command: npm start
    volumes:
      - ./node:/app/
      - /app/node_modules
    depends_on:
      - mysql
    container_name: node
